[id='rn-BAMOE-8.0.5-known-issues-ref']
= Known limitations in {PRODUCT} 8.0.5

This section lists known limitations with {PRODUCT} 8.0.5.

[NOTE]
====
Review the information on the https://www.ibm.com/support/pages/node/6596921[IBM Business Automation Manager Open Editions {ENTERPRISE_VERSION} known limitations] page for limitations identified after release.
====

== {CENTRAL}

.Business Central EAP7 deployable ZIP 8.0.5 cannot be updated with the update tool
//[https://issues.redhat.com/browse/RHPAM-4841[RHPAM-4841]]

Issue:

If you use the update tool to update an {PRODUCT} 8.0.4 `rhpam-business-central-eap7-deployable` installation to release 8.0.5.SP1 (8.0.5-IF001), the update fails with the following error:

[source]
----
ERROR - The patch is not valid for the distribution and version!
----

Workaround:

. Open the `standalone/deployments/business-central.war/META-INF/MANIFEST.MF` file in a text editor.
. Edit the implementation version and save the file:
+
[source]
----
Implementation-Version: 7.67.2.Final-redhat-00008
----

. Run the update tool again.

NOTE: This issue only affects the `business-central.war` file in the 8.0.4 distribution. KIE Server is not affected and other versions such as 8.0.3 or 8.0.4-IF001 are not affected.
